In [1]:
import tensorflow as tf

2023-03-03 15:31:01.816456: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-03 15:31:02.265582: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64::/usr/local/cuda-11.2/lib64:
2023-03-03 15:31:02.265622: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64::/usr/local/cuda-11.2/lib64:
2023-03-03 15:31:0

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

2023-03-03 15:31:02.806314: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-03 15:31:02.810682: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-03 15:31:02.810850: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-03 15:31:02.811692: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorF

In [3]:
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
len(dataset)

6

In [5]:
for elem in dataset:
  print(elem.numpy())

8
3
0
8
2
1


In [6]:
it = iter(dataset)

print(next(it).numpy())
print(next(it).numpy())
print(next(it).numpy())

8
3
0


In [7]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
22


In [8]:
print(dataset.reduce(5, lambda state, value: state + value).numpy())

27


In [9]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [10]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [11]:
tf.random.uniform([4, 10])

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.60961974, 0.14195287, 0.56842613, 0.52302   , 0.6738534 ,
        0.88964665, 0.5754889 , 0.22995663, 0.44261754, 0.60117817],
       [0.7139089 , 0.03809655, 0.62570465, 0.9671459 , 0.8951957 ,
        0.77446425, 0.24921644, 0.8977852 , 0.39549196, 0.07810843],
       [0.35035217, 0.483595  , 0.7953185 , 0.895053  , 0.893644  ,
        0.4918188 , 0.5166904 , 0.71212304, 0.89914584, 0.5918118 ],
       [0.44696188, 0.1891824 , 0.7148801 , 0.29798222, 0.29623795,
        0.39439225, 0.6699985 , 0.58090794, 0.82338727, 0.29670835]],
      dtype=float32)>

In [12]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))

dataset1

<TensorSliceDataset element_spec=TensorSpec(shape=(10,), dtype=tf.int32, name=None)>

In [13]:
for z in dataset1:
  print(z.numpy())

[8 8 4 9 2 2 3 8 9 6]
[4 7 8 2 4 2 8 8 8 3]
[5 7 7 3 7 9 8 6 6 3]
[2 6 1 7 5 8 7 8 2 2]


In [14]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))>

In [15]:
len(dataset2)

4

In [16]:
for i in dataset2:
    print(i)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.7055193>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([84, 82, 92, 38, 13, 48, 80, 54, 61, 90, 79, 32, 33, 30, 94, 99, 17,
       12, 77, 40,  7, 18, 93, 65,  8, 16, 74, 39, 41, 84,  2, 72, 99, 15,
       45, 95, 46,  6, 38, 69, 97,  5, 71, 38, 11, 21, 22, 71, 44, 80, 37,
       14, 93, 74, 54, 61, 74, 20, 21, 50, 95, 60, 66, 25, 72, 10, 84, 10,
       90, 35, 28, 62, 54, 32, 98, 48, 60, 18, 66, 37, 20, 54, 26, 15, 98,
       59, 66, 74, 28, 60, 91, 53, 56, 57,  4, 43, 52, 91, 25, 95],
      dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.7817211>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([90, 58, 82,  9, 69, 42,  7, 32, 65, 84, 88, 53, 81, 37, 63, 93, 76,
       67, 93, 74, 59, 71, 21, 88, 57, 45, 85, 16, 78, 20, 14, 58, 99, 13,
       61,  9, 28, 98, 29, 16, 86,  5, 97, 83, 97, 17, 30, 85, 59, 44, 90,
       98, 56, 88, 98, 46,  4, 47, 13, 75, 41, 33,  0, 25, 82, 24, 50, 57,
       93, 84, 87, 64, 28, 18, 8

In [17]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [3, 5, 4]])


for i in dataset:
    print(i)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 5 4], shape=(3,), dtype=int32)


In [18]:
dataset.shape()

AttributeError: 'TensorSliceDataset' object has no attribute 'shape'

In [ ]:
len(dataset)

In [ ]:
dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4, 100]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

In [ ]:
# for i in dataset2:
#    print(i)
    
len(dataset2)

In [ ]:
tf.random.uniform([4, 1, 1])

In [ ]:
(tf.random.uniform([4, 1]),
    tf.random.uniform([4, 1], maxval=100, dtype=tf.int32))

In [ ]:
dataset2 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 1]))

In [ ]:
for i in dataset2:
    print(i)

In [ ]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 1], maxval=100, dtype=tf.int32)))

dataset2.element_spec

In [ ]:
for i in dataset2:
    print(i)

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 1]))

#dataset1.element_spec


dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([1]),
    tf.random.uniform([1, 2], maxval=100, dtype=tf.int32)))

#dataset2.element_spec


dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

dataset3.element_spec


for i in dataset3:
    print(i)
    

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([1, 1]), tf.random.uniform([1, 1])))

dataset2 = tf.data.Dataset.from_tensors(
    (tf.random.uniform([1, 1]), tf.random.uniform([1, 1])))

for i, item in enumerate(dataset1):
    print('element: ' + str(i + 1), item[0], item[1])

print(30*'-')

for i, item in enumerate(dataset2):
    print('element: ' + str(i + 1), item[0], item[1])

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    [tf.random.uniform([2, 3]), tf.random.uniform([2, 3])])

dataset2 = tf.data.Dataset.from_tensors(
    [tf.random.uniform([2, 3]), tf.random.uniform([2, 3])])

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    [tf.random.uniform([2, 3]), tf.random.uniform([2, 3])])

dataset2 = tf.data.Dataset.from_tensors(
    [tf.random.uniform([2, 3]), tf.random.uniform([2, 3])])

print(dataset1) # shapes: (2, 3)
print(dataset2) # shapes: (2, 2, 3)

In [ ]:
len(dataset1)

In [ ]:
len(dataset2)

In [ ]:
for i in dataset2:
    print(i)

In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 1], minval=1, maxval=10, dtype=tf.int32))

dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 2], maxval=100, dtype=tf.int32)))


In [ ]:
dataset1
dataset2

In [ ]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3

In [ ]:
for i in dataset1:
    print(i)

In [ ]:
for i in dataset2:
    print(i)

In [ ]:
for i in dataset3:
    print(i)
    

In [19]:
import tensorflow_datasets as tfds

(ds_train, ds_test), ds_info = tfds.load('fashion_mnist', data_dir='.',
                                             split=['train', 'test'], shuffle_files=True,
                                             as_supervised=True,
                                             with_info=True)





/home/fusionsystems/Dokumente/gpa/tensorflow/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
for image, label in ds_train:
    # we get only single image
    print(image.shape()) # ()
    print(label.shape())